# Neden Numpy?

#### 1) optimizasyon anlamında yazılımsal anlamda veri saklama konusunda bir iyileştirme sunar
#### 2) yüksek seviye vektörel operasyonlar,nümerik hesaplar yapmamızı sağlar

In [30]:
a=[1,2,3,4]
b=[2,3,4,5]
a
b  # en sona b yazdigimiz icin b degerleri gelir ekrana

[2, 3, 4, 5]

In [31]:
#elimzide iki listeyi birbiriyle çarpmak istiyoruz.
#fonksiyonel programlama 
#ile nasıl yapmıştık?(nesne yönelimli programlama 
#özellikleriyle ele aldığımızda)

ab = []

for i in range (0,len(a)):
 ab.append(a[i]*b[i])

ab


[2, 6, 12, 20]

 ##### Daha karmaşık işlemler  olunca(örneğin matris çarpımı vs.) tek tek kod yazmak zor olacağından Numpy, yüksek seviye ile araya girip hoop ben burdayım der. tek tek kod yazmaya gerek yok
 
 
 


In [14]:
import numpy as np 
#numpy kütüphanesini 
#np adıyla(kendimiz bu kısa adı verdik)çağırdık 

In [19]:
a=np.array([1,2,3,4]) 
b=np.array([2,3,4,5])
#numpy arrayler tıpkı liste,tuple gibi bir veri tipidir.
#numpy içerisinde yer alan bir veri tipidir

In [18]:
a*b  #daha yeni kod yazarak yaptığımız işlemi çok kolay 
     #bir şekilde yapmamızı sağladı

array([ 2,  6, 12, 20])

### NumPy Array'i Oluşturmak

In [22]:
import numpy as np

In [23]:
np.array([1,2,3,4,6])

array([1, 2, 3, 4, 6])

In [24]:
type(a)

numpy.ndarray

In [29]:
np.array([3.14 , 4 , 2 , 13]) 

#tek bir float değeri oldugundan hepsini float'a çevirdi
#(sabit tip baskısı)

array([ 3.14,  4.  ,  2.  , 13.  ])

In [30]:
np.array([3.14 , 4 , 2 , 13],dtype="int") 

#kod içerisinde int olarak tanımladığımız için 
#float olsada int çevirdi
#hepsini tek tip yaptı


array([ 3,  4,  2, 13])

##### Sıfırdan Array Oluşturma

In [32]:
np.zeros(10,dtype="int") 
#10 tane 0 dan olusan değer oluşmuş oldu

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [35]:
np.ones((3,5),dtype="int")
#3 satır 5 sütun 1lerden olusan bir array olusturduk

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [38]:
np.full((3,5),3) 
#3'e 5'lik 3'lerden oluşan bir array

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [39]:
np.arange(0,31,3) 
#0dan 31e kadar 3er 3er aratacak şekilde 
#doğrusal bir dizi olusturduk

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [40]:
np.linspace(0,1,10)
#0 ile 21 arasında 10 sayı olustur

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [42]:
np.random.normal(10,4,(3,4))
#ort=10 s.sapması=4 3,4'ük matris 

array([[ 6.3576919 , 10.62374863, 12.15674061, 11.4000117 ],
       [11.83976582, 13.27998568,  8.44206395, 13.2096407 ],
       [10.50338989,  8.84620086, 16.81981378,  6.21938467]])

In [43]:
np.random.randint(0,10,(3,3))
#0-10 arasında 3,3lük matris olusturma(int)

array([[1, 0, 0],
       [0, 5, 7],
       [8, 6, 8]])

### NumPy Array Özellikleri

* **ndim** : boyut sayısı
* **shape** : boyut bilgisi
* **size** : toplam eleman sayısı
* **dtype** : array veri tipi

In [44]:
import numpy as np

In [49]:
np.random.randint(10,size=10)

array([4, 2, 5, 7, 5, 0, 3, 2, 0, 8])

In [47]:
a=np.random.randint(10,size=10)

In [48]:
a.ndim #tek boyutlu

1

In [50]:
a.shape #boyut içerisinde ki bilgi

(10,)

In [51]:
a.size #toplam eleman sayısı

10

In [52]:
a.dtype #içerisinde ki int tipini vermiş oldu

dtype('int32')

In [53]:
np.random.randint(10, size=(3,5))

array([[5, 8, 1, 4, 9],
       [4, 1, 8, 9, 1],
       [7, 4, 1, 7, 7]])

In [54]:
b=np.random.randint(10, size=(3,5))

In [55]:
b.ndim #iki boyutlu

2

In [56]:
b.shape #bir boyutta 3 diger boyutta 5 eleman var

(3, 5)

In [57]:
b.size #tüm array içersindeki toplam eleman sayısı

15

In [58]:
b.dtype

dtype('int32')

### NumPy Array'i Yeniden Şekillendirme (Reshaping)

In [59]:
import numpy as np

In [60]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
 np.arange(1,10).reshape(3,3) #tek boyutu üç boyuta çevirdi

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
a=np.arange(1,10)

In [63]:
a #tek boyutlu bir array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
a.ndim

1

In [65]:
a.reshape((1,9))
#1 satır 9 sütuna çevirdik yani 2 boyuta çevirdik

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [66]:
b=a.reshape((1,9))

In [67]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [70]:
#a ile b aynı çıktı gibi görünüyor fakat 
#a tek boyutlu b iki boyutlu

### NumPy Array'i Birleştirme (Concatenation)

In [71]:
import numpy as np

In [72]:
x=np.array([1,2,3])
y=np.array([4,5,6])

In [78]:
#tek boyut birleştirme

In [75]:
np.concatenate([x,y]) 

array([1, 2, 3, 4, 5, 6])

In [76]:
z=np.array([7,8,9])

In [77]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
#iki boyut birleştirme

In [80]:
a=np.array([[1,2,3],
          [4,5,6]])

In [81]:
np.concatenate([a,a]) 

#satır bazında birleştirdi(ön tanımlıdır.axis=0'dır)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [82]:
np.concatenate([a,a],axis=1) 

#sütun bazında birleştirdi

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

### NumPy Array'i Ayırma (Splitting)

In [83]:
import numpy as np

In [84]:
x=np.array([1,2,3,99,99,3,2,1])

In [85]:
np.split(x , [3,5]) 
#indeks numaraları girerek kaça kadar bölmek istedigimizi gördük
#3.indeksekadar böl sonrasında da 5.indekse kadar böl
#iki indeks verdiğimizde 3 array oluşturur(bir fazlası)

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

her bir arrayi bir degiskene atadık 
böylelikle ayırdığımız arrayleri kullanabiliriz

In [86]:
a,b,c=np.split(x , [3,5]) 

In [87]:
a

array([1, 2, 3])

In [88]:
b

array([99, 99])

In [89]:
c

array([3, 2, 1])

**İKİ BOYUTLU AYIRMA**

In [91]:
m=np.arange(16).reshape(4,4)

In [92]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

_ikinci satırdan sonraki kısmı bölüp dikey olarak yana eklemek 
istediğimizi düşünelim?_

In [93]:
np.split(m,[2])
#satır olarak böldük

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [94]:
ust,alt =np.split(m,[2])

In [95]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [96]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [97]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [100]:
np.hsplit(m,[2])  
#satırdan değil sütundan böldük

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [101]:
sag , sol=np.hsplit(m,[2])  


In [102]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [103]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

### NumPy Array'i Sıralama (Sorting)

In [104]:
import numpy as np

In [105]:
v=np.array([2,1,4,3,5])

In [108]:
v

array([2, 1, 4, 3, 5])

In [107]:
np.sort(v)
#küçükten büyüğe sıraladı
#veri setinin orjinal yapısını bozmadı

array([1, 2, 3, 4, 5])

In [109]:
v.sort()
#baska bir sort fonksiyonu yapısını bozmuş oldu

In [110]:
v 

array([1, 2, 3, 4, 5])

**İKİ BOYUTLU ARRAY SIRALAMA**

In [113]:
m=np.random.normal(20,5,(3,3))

In [114]:
m

array([[21.18972843, 26.43185327, 13.61087888],
       [17.30259895, 17.45389857, 20.76153478],
       [13.15351368, 23.89122804, 22.41875142]])

_satırları sıralamak isteyelim_

In [115]:
np.sort(m,axis=1)

array([[13.61087888, 21.18972843, 26.43185327],
       [17.30259895, 17.45389857, 20.76153478],
       [13.15351368, 22.41875142, 23.89122804]])

_sütunları sıralamak isteyelim_

In [116]:
np.sort(m,axis=0)

array([[13.15351368, 17.45389857, 13.61087888],
       [17.30259895, 23.89122804, 20.76153478],
       [21.18972843, 26.43185327, 22.41875142]])

###  Index Elemana Erişmek

In [119]:
import numpy as np
a=np.random.randint(10,size=10)
a

array([2, 8, 7, 0, 1, 3, 1, 0, 6, 0])

In [120]:
a[0] #birinci elemana erişmek istersek

2

In [121]:
a[-1] #terstten birinci elema erişmek istersek

0

In [122]:
a[0]=100 #ilk elemanı değiştirdik 100 yaptık

In [123]:
a

array([100,   8,   7,   0,   1,   3,   1,   0,   6,   0])

In [124]:
m=np.random.randint(10,size=(3,5))
m

array([[1, 0, 6, 3, 6],
       [4, 1, 8, 1, 2],
       [6, 0, 9, 3, 2]])

In [125]:
m[0,0]

1

In [129]:
m[2,0]

6

In [131]:
m[2,0]=99

In [132]:
m

array([[ 1,  0,  6,  3,  6],
       [ 4,  1,  8,  1,  2],
       [99,  0,  9,  3,  2]])

In [133]:
m[1,4]=2.2 #float eklemiş olsakta int çevirdi

In [134]:
m

array([[ 1,  0,  6,  3,  6],
       [ 4,  1,  8,  1,  2],
       [99,  0,  9,  3,  2]])

### Array Alt Küme İşlemleri(Slicing)

**Slice** : _şurdan şuraya kadar git,dilimle ( örneğin [0:3] )_

In [135]:
import numpy as np

In [136]:
a=np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [138]:
a[1::2]

#1.indeksten başlayarak  2 şer giderek seçmiş sonuna kadar

array([21, 23, 25, 27, 29])

**İKİ BOYUTLU SLİCE İŞLEMLERİ**

In [139]:
m=np.random.randint(10,size=(5,5))

In [140]:
m

array([[0, 2, 8, 5, 3],
       [5, 6, 8, 8, 8],
       [6, 9, 1, 2, 3],
       [3, 0, 1, 1, 4],
       [6, 1, 6, 6, 9]])

In [141]:
m[:,0] #bütün satırı ve 0.sütunu ver

array([0, 5, 6, 3, 6])

In [142]:
m[2,:] #bütün sütun ve 2.satırı ver

array([6, 9, 1, 2, 3])

In [143]:
m[0:2 , 0:3] #2.satıra kadar ve 3.sütuna kadar olanları getir

array([[0, 2, 8],
       [5, 6, 8]])

In [144]:
m[::,:2] #bütün satırları al ve 2.sütuna kadarları al

array([[0, 2],
       [5, 6],
       [6, 9],
       [3, 0],
       [6, 1]])

In [145]:
m[:,:2] #üstteki hücreyle aynı şey

array([[0, 2],
       [5, 6],
       [6, 9],
       [3, 0],
       [6, 1]])

In [146]:
m

array([[0, 2, 8, 5, 3],
       [5, 6, 8, 8, 8],
       [6, 9, 1, 2, 3],
       [3, 0, 1, 1, 4],
       [6, 1, 6, 6, 9]])

In [147]:
m[1:3,:2]
#1den 3.satıra kadar gel,
#0dan 2.sütuna kadar git ve kesişimini al

array([[5, 6],
       [6, 9]])

### Alt Küme Üzerinde İşlem Yapmak

In [2]:
import numpy as np
a=np.random.randint(10,size=(5,5))
a

array([[2, 4, 0, 1, 5],
       [5, 2, 2, 3, 2],
       [3, 7, 2, 5, 9],
       [7, 9, 0, 3, 5],
       [1, 0, 6, 3, 3]])

_bir arrayin alt kümesine eriştikten sonra isimlendirip kaydettiğimizi düşünelim.bu kaydetmiş olduğumuz isimlendirme üzerine bir değişiklik yaptığımızda arrayin ilk halinde de değişiklik olmakta. fakat bazen o alt kümeye özel işlemler yapılmak istenebilir.o alt kümeye özel kalmasını isteriz._

In [4]:
alt_a=a[0:3,0:2]
alt_a

array([[2, 4],
       [5, 2],
       [3, 7]])

In [5]:
alt_a[0,0]=999
alt_a[1,1]=88

In [6]:
alt_a

array([[999,   4],
       [  5,  88],
       [  3,   7]])

In [7]:
a   #alt_a işlemi a'nın değerlerinde değişiklik sağladı

array([[999,   4,   0,   1,   5],
       [  5,  88,   2,   3,   2],
       [  3,   7,   2,   5,   9],
       [  7,   9,   0,   3,   5],
       [  1,   0,   6,   3,   3]])

In [8]:
#bu özelleştirmeyi copy fonksiyonu ile düzeltiriz

In [10]:
m=np.random.randint(10,size=(5,5))
m

array([[1, 4, 3, 5, 3],
       [2, 2, 0, 0, 6],
       [8, 0, 4, 7, 1],
       [4, 6, 6, 6, 3],
       [5, 5, 4, 2, 5]])

In [12]:
alt_b=m[0:3,0:2].copy()
alt_b

array([[1, 4],
       [2, 2],
       [8, 0]])

In [14]:
alt_b[0,0]=555
alt_b

array([[555,   4],
       [  2,   2],
       [  8,   0]])

In [15]:
m 
#oluşturmuş olduğumuz ilk arrayin yapısında 
#hiçbir değişiklik meydana gelmedi 

array([[1, 4, 3, 5, 3],
       [2, 2, 0, 0, 6],
       [8, 0, 4, 7, 1],
       [4, 6, 6, 6, 3],
       [5, 5, 4, 2, 5]])

## Fancy Index ile Elemanlara Erişmek

In [16]:
import numpy as np
v=np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

tek tek elemanalra erişmek istersek

In [17]:
v[1]

3

In [18]:
v[3]

9

In [19]:
v[5]

15

üçüne aynı anda erişmek istersek

In [20]:
[v[1],v[3],v[5]]

[3, 9, 15]

Yüzlerce indeksli veride ne yapacağız? elle tek tek çağıramayız!!

Sorgulama işlemini bir kerede yapmamızı sağlar Fancy Indekstir

In [21]:
al_getir=[1,3,5]

In [23]:
v[al_getir] ### Buna Fancy Indeks denir

array([ 3,  9, 15])

In [24]:
#İKİ boyutta Fancy

In [25]:
m=np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
satir=np.array([0,1])
sütun=np.array([1,2])

In [27]:
m[satir,sütun] #FANCY!

array([1, 5])

In [32]:
#basit index ile fancy indeks
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [33]:
m[0,[1,2]] #basit index ile facy kullandık

array([1, 2])

In [35]:
m[0:,[1,2]] #slice ile fancy kullandık

array([[1, 2],
       [4, 5],
       [7, 8]])

### Koşullu Eleman İşlemleri

In [36]:
import numpy as np
v=np.array([1,2,3,4,5])

In [38]:
v < 3 # v arrayinin içindekiler 3den küçük mu

array([ True,  True, False, False, False])

In [40]:
v[v < 3] # şu sorgu sonucunu sağlayan değerleri görmek istiyorum
         #Fancy indekstir

array([1, 2])

### Matematiksel İşlemler


In [42]:
import numpy as np
v=np.array([1,2,3,4,5])

In [44]:
v*2 #bütün elemanları 2 ile çarptık

array([ 2,  4,  6,  8, 10])

In [45]:
#ufunc=yıldız yazmış olsakta arka da bazı işlemler yapılıyor

In [46]:
np.multiply(v,2) # yukarıda v*2 yazıp sonucu aldık fakat
                 #numpy arkada bu şekilde yaptı(ufunc)

array([ 2,  4,  6,  8, 10])

In [47]:
v % 2 #vnin 2 ye bölümünden kalanlar geldi

array([1, 0, 1, 0, 1], dtype=int32)

In [48]:
np.mod(v,2) #2ye bölümünden kalanları getir.(ufunc)

array([1, 0, 1, 0, 1], dtype=int32)

In [50]:
np.absolute(np.array([-3])) #mutlak değeri (ufunc)

array([3])

In [51]:
np.sin(360)

0.9589157234143065

In [52]:
v=np.array([1,2,3])

In [53]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [55]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [57]:
?np # numpy ile ilgili kullanılabilecek yapıların bilgileri

Type:        module
String form: <module 'numpy' from 'C:\\Users\\basak\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\basak\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >

### İstatistiksel Hesaplamalar

In [58]:
np.mean(v)

2.0

In [59]:
v.sum() #içindekileri topladı

6

### NumPy ile İki Bilinmeyenli Denklem Çözümü

In [60]:
import numpy as np

5 * x0 + x1 = 12

x0 + 3 * x1 = 10

In [61]:
a=np.array([[5,1],[1,3]])
b=np.array([12,10])

In [62]:
a

array([[5, 1],
       [1, 3]])

In [63]:
b

array([12, 10])

In [64]:
x=np.linalg.solve(a,b)
x                      #x0 ve x1 değerlerini bulmuş olduk

array([1.85714286, 2.71428571])